export const SHOP_DATA = {
    glasses: {
        id: 1,
        'name': 'GLASSES',
        'image': '/glasses.jpg',
        routeName: 'shop/glasses',
        items: [
            {
                'name': 'LYA',
                'price': '199',
                'brand': 'LYA',
                'category': 'glasses',
                'variant': 'Gray',
                'quantity': 1,
                image: '/glasses/lya.jpg',
                isAddedToCart: false,
                id: 1,
            },
            {
                'name': 'ALFRED SUNG',
                'price': '279',
                'brand': 'ALFRED SUNG',
                'category': 'glasses',
                'variant': 'Gray',
                'quantity': 1,
                image: '/glasses/alfredSung.jpg',
                isAddedToCart: false,
                id: 2,
            },
            {
                'name': 'OGI',
                'price': '289',
                'brand': 'OGI',
                'category': 'glasses',
                'variant': 'Gray',
                'quantity': 1,
                image: '/glasses/ogi.jpg',
                isAddedToCart: false,
                id: 3,
            }, {
                'name': 'NIKE',
                'price': '267',
                'brand': 'NIKE',
                'category': 'glasses',
                'variant': 'Gray',
                'quantity': 1,
                image: '/glasses/nike.jpg',
                isAddedToCart: false,
                id: 4,
            },

        ]
    },
    hats: {
        id: 2,
        'name': 'HATS',
        'image': '/hats.jpg',
        routeName: 'shop/hats',
        items: [
            {
                'name': 'Brown Brim',
                'price': '15',
                'brand': 'HATS',
                'category': 'hats',
                'variant': 'Gray',
                'quantity': 1,
                image: '/hats/brown-brim.png',
                isAddedToCart: false,
                id: 5,
            },
            {
                'name': 'Blue Beanie',
                'price': '18',
                'brand': 'HATS',
                'category': 'hats',
                'variant': 'Gray',
                'quantity': 1,
                image: '/hats/blue-beanie.png',
                isAddedToCart: false,
                id: 6,
            },
            {
                'name': 'Brown Cowboy',
                'price': '13',
                'brand': 'HATS',
                'category': 'hats',
                'variant': 'Gray',
                'quantity': 1,
                image: '/hats/brown-cowboy.png',
                isAddedToCart: false,
                id: 7,
            }, {
                'name': 'Grey Brim',
                'price': '19',
                'brand': 'HATS',
                'category': 'hats',
                'variant': 'Gray',
                'quantity': 1,
                image: '/hats/grey-brim.png',
                isAddedToCart: false,
                id: 8,
            }, {
                'name': 'Green Beanie',
                'price': '12',
                'brand': 'HATS',
                'category': 'hats',
                'variant': 'Gray',
                'quantity': 1,
                image: '/hats/green-beanie.png',
                isAddedToCart: false,
                id: 9,
            }, {
                'name': 'Palm Tree Cap',
                'price': '18',
                'brand': 'HATS',
                'category': 'hats',
                'variant': 'Gray',
                'quantity': 1,
                image: '/hats/palm-tree-cap.png',
                isAddedToCart: false,
                id: 10,
            }, {
                'name': 'Red Beanie',
                'price': '28',
                'brand': 'HATS',
                category: 'hats',
                'variant': 'Gray',
                'quantity': 1,
                image: '/hats/red-beanie.png',
                isAddedToCart: false,
                id: 11,
            }, {
                'name': 'Wolf Cap',
                'price': '33',
                'brand': 'HATS',
                'category': 'hats',
                'variant': 'Gray',
                'quantity': 1,
                image: '/hats/wolf-cap.png',
                isAddedToCart: false,
                id:12
            },

        ]
    },
    "mens": {
        id: 3,
        routeName: 'shop/mens',
        'name': 'MENS',
        'image': '/mens.jpg',
        items: [
            {
                'name': 'Camo Down Vest',
                'price': '120',
                'brand': 'MENS',
                'category': 'mens',
                'variant': 'Gray',
                'quantity': 1,
                id: 13,
                image: '/mens/camo-vest.png',
                isAddedToCart: false,
            }, {
                'name': 'Floral T-shirt',
                'price': '30',
                'brand': 'MENS',
                'category': 'mens',
                'variant': 'Gray',
                'quantity': 1,
                id: 14,
                image: '/mens/floral-shirt.png',
                isAddedToCart: false,
            }, {
                'name': 'Black & White Longsleeve',
                'price': '20',
                'brand': 'MENS',
                'category': 'mens',
                'variant': 'Gray',
                'quantity': 1,
                id: 15,
                image: '/mens/long-sleeve.png',
                isAddedToCart: false,
            }, {
                'name': 'Pink T-shirt',
                'price': '25',
                'brand': 'MENS',
                'category': 'mens',
                'variant': 'Gray',
                'quantity': 1,
                id: 16,
                image: '/mens/pink-shirt.png',
                isAddedToCart: false,
            }
        ]
    },
    womens: {
        id: 4,
        routeName: 'shop/womens',
        'name': 'WOMENS',
        'image': '/womens.jpg',
        items: [
            {
                'name': 'Blue Tanktop',
                'price': '50',
                'brand': 'WOMENS',
                'category': 'womens',
                'variant': 'Gray',
                'quantity': 1,
                image: '/womens/blue-tank.png',
                isAddedToCart: false,
                id: 17,
            },{
                'name': 'Floral Blouse',
                'price': '45',
                'brand': 'WOMENS',
                'category': 'womens',
                'variant': 'Gray',
                'quantity': 1,
                image: '/womens/floral-blouse.png',
                isAddedToCart: false,
                id: 18,
            },{
                'name': 'Floral Dress',
                'price': '40',
                'brand': 'WOMENS',
                'category': 'womens',
                'variant': 'Gray',
                'quantity': 1,
                image: '/womens/floral-skirt.png',
                isAddedToCart: false,
                id: 19,
            },{
                'name': 'Red Dots Dress',
                'price': '150',
                'brand': 'WOMENS',
                'category': 'womens',
                'variant': 'Gray',
                'quantity': 1,
                image: '/womens/red-polka-dot-dress.png',
                isAddedToCart: false,
                id: 20,
            },

        ]
    },
    jackets: {
        id: 5,
        routeName: 'shop/jackets',
        'name': 'JACKETS',
        'image': '/jackets.jpg',
        items: [
            {
                'name': 'Black Jean Shearling',
                'price': '150',
                'brand': 'JACKETS',
                'category': 'jackets',
                'variant': 'Gray',
                'quantity': 1,
                image: '/jackets/black-shearling.png',
                isAddedToCart: false,
                id: 21,
            }, {
                'name': 'Blue Jean Jacket',
                'price': '160',
                'brand': 'JACKETS',
                'category': 'jackets',
                'variant': 'Gray',
                'quantity': 1,
                image: '/jackets/blue-jean-jacket.png',
                isAddedToCart: false,
                id: 22,
            }, {
                'name': 'Grey Jean Jacket',
                'price': '170',
                'brand': 'JACKETS',
                'category': 'jackets',
                'variant': 'Gray',
                'quantity': 1,
                image: '/jackets/grey-jean-jacket.png',
                isAddedToCart: false,
                id: 23,
            }, {
                'name': 'Brown Shearling',
                'price': '200',
                'brand': 'JACKETS',
                'category': 'jackets',
                'variant': 'Gray',
                'quantity': 1,
                image: '/jackets/brown-shearling.png',
                isAddedToCart: false,
                id: 24,
            },


        ]
    },
    sneakers: {
        id: 6,
        routeName: 'shop/sneakers',
        'name': 'SNEAKERS',
        'image': '/sneakers.jpg',
        items: [
            {
                'name': 'Adidas NMD',
                'price': '350',
                'brand': 'SNEAKERS',
                'category': 'sneakers',
                'variant': 'Gray',
                'quantity': 1,
                image: '/sneakers/adidas-nmd.png',
                isAddedToCart: false,
                id: 25,
            },
            {
                'name': 'Adidas Yeezy',
                'price': '300',
                'brand': 'SNEAKERS',
                'category': 'sneakers',
                'variant': 'Gray',
                'quantity': 1,
                image: '/sneakers/yeezy.png',
                isAddedToCart: false,
                id: 26,
            }, {
                'name': 'Black Converse',
                'price': '150',
                'brand': 'SNEAKERS',
                'category': 'sneakers',
                'variant': 'Gray',
                'quantity': 1,
                image: '/sneakers/black-converse.png',
                isAddedToCart: false,
                id: 27,
            }, {
                'name': 'Nike White AirForce',
                'price': '190',
                'brand': 'SNEAKERS',
                'category': 'sneakers',
                'variant': 'Gray',
                'quantity': 1,
                image: '/sneakers/white-nike-high-tops.png',
                isAddedToCart: false,
                id: 28,
            }, {
                'name': 'Nike Red High Tops',
                'price': '200',
                'brand': 'SNEAKERS',
                'category': 'sneakers',
                'variant': 'Gray',
                'quantity': 1,
                image: '/sneakers/nikes-red.png',
                isAddedToCart: false,
                id: 29,
            }, {
                'name': 'Nike Brown High Tops',
                'price': '200',
                'brand': 'SNEAKERS',
                'category': 'sneakers',
                'variant': 'Gray',
                'quantity': 1,
                image: '/sneakers/nike-brown.png',
                isAddedToCart: false,
                id: 30,
            }, {
                'name': 'Air Jordan Limited',
                'price': '220',
                'brand': 'SNEAKERS',
                'category': 'sneakers',
                'variant': 'Gray',
                'quantity': 1,
                image: '/sneakers/nike-funky.png',
                isAddedToCart: false,
                id: 31,
            }, {
                'name': 'Timberlands',
                'price': '250',
                'brand': 'SNEAKERS',
                'category': 'sneakers',
                'variant': 'Gray',
                'quantity': 1,
                image: '/sneakers/timberlands.png',
                isAddedToCart: false,
                id: 32,
            },

        ]
    }


}