// export const TOGGLE_HAT_CART = 'TOGGLE_HAT_CART';
// export const ADD_ONE_HAT = 'ADD_ONE_EHAT';
// export const SUB_ONE_HAT = 'SUB_ONE_HAT';
//
// export const TOGGLE_SNEAKER_CART = 'TOGGLE_SNEAKERS_CART';
// export const SUB_ONE_SNEAKER = 'SUB_ONE_SNEAKER';
// export const ADD_ONE_SNEAKER = 'ADD_ONE_SNEAKER';
//
// export const TOGGLE_MEN_CART = 'TOGGLE_MEN_CART';
// export const ADD_ONE_MEN = 'ADD_ONE_MEN';
// export const SUB_ONE_MEN = 'SUB_ONE_MEN';
//
// export const TOGGLE_WOMEN_CART = 'TOGGLE_WOMEN_CART';
// export const ADD_ONE_WOMEN = 'ADD_ONE_WOMEN';
// export const SUB_ONE_WOMEN = 'SUB_ONE_WOMEN';
//
// export const TOGGLE_JACKET_CART = 'TOGGLE_JACKET_CART';
// export const ADD_ONE_JACKET = 'ADD_ONE_JACKET';
// export const SUB_ONE_JACKET = 'SUB_ONE_JACKET';
//
//
// export const TOGGLE_GLASS_CART = 'TOGGLE_GLASS_CART';
// export const ADD_ONE_GLASS = 'ADD_ONE_GLASS';
// export const SUB_ONE_GLASS = 'SUB_ONE_GLASS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const ADD_ONE_ITEM = 'ADD_ONE_ITEM';
export const REMOVE_ONE_ITEM = 'REMOVE_ONE_ITEM';


export const ADD_ONE_ITEM_TO_CARTED_PRODUCTS = 'ADD_ONE_ITEM_TO_CARTED_PRODUCTS';
export const REMOVE_ONE_ITEM_FROM_CARTED_PRODUCTS = 'REMOVE_ONE_ITEM_FROM_CARTED_PRODUCTS';

export const FETCH_COLLECTION_START = 'FETCH_COLLECTION_START';
export const FETCH_COLLECTION_FAILURE = 'FETCH_COLLECTION_FAILURE';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';

export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_OUT_START = 'SIGN_OUT_START';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const CLEAR_CART = 'CLEAR_CART';

export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';


